---
- name: Enable CRB repository
  command: '{{ packaging.command }} config-manager --set-enabled crb -y'
  when:
    - (os.name == 'CentOS' and os.version == 'Stream9') or
      (os.name == 'AlmaLinux' and os.version == '9')

- name: Enable PowerTools repository
  command: '{{ packaging.command }} config-manager --set-enabled powertools -y'
  when:
    - (os.name == 'CentOS' and os.version == 'Stream8') or
      (os.name == 'AlmaLinux' and os.version == '8')

- name: Enable EPEL repository
  package:
    name: epel-release
    state: latest
  when:
    - os.name == 'CentOS' or os.name == 'AlmaLinux'

- name: Enable EPEL Next repository
  package:
    name: epel-next-release
    state: latest
  when:
    - os.name == 'CentOS'
    - os.version == 'Stream8' or os.version == 'Stream9'

- name: Enable Advanced Virtualization repository
  package:
    name: centos-release-advanced-virtualization
    state: latest
  when:
    - (os.name == 'CentOS' and os.version == 'Stream8') or
      (os.name == 'AlmaLinux' and os.version == '8')
