---
- name: Open vault
  include_vars:
    file: vars/vault.yml

- name: Look up Jenkins secret
  set_fact:
    jenkins_secret: '{{ vault.jenkins_secrets[inventory_hostname] }}'

- name: Create Jenkins user account
  user:
    name: jenkins
    comment: Jenkins
    password: '*'

- name: Download Jenkins agent
  get_url:
    url: https://ci.centos.org/jnlpJars/slave.jar
    dest: /home/jenkins/slave.jar
    owner: jenkins
    group: jenkins
    force: yes

- name: Configure and enable Jenkins agent
  lineinfile:
    path: /etc/rc.local
    create: yes
    backup: yes
    regexp: '^nohup.*jenkins.*java.*slave\.jar.*&$'
    line: "nohup {{ su }} - jenkins -c '{{ java }} -jar /home/jenkins/slave.jar -jnlpUrl \"{{ jenkins_url }}\" -secret \"{{ jenkins_secret }}\"' >/var/log/jenkins.log 2>&1 &"
    insertbefore: '^exit .*$'
  when:
    - ansible_service_mgr != 'systemd'

- name: Configure Jenkins agent
  template:
    src: templates/jenkins.service.j2
    dest: /etc/systemd/system/jenkins.service
  when:
    - ansible_service_mgr == 'systemd'

- name: Enable Jenkins agent
  systemd:
    name: jenkins.service
    enabled: yes
    daemon_reload: yes
  when:
    - ansible_service_mgr == 'systemd'
