export PS1="[\u@\h \w]\$ "

export VIRT_PREFIX="{{ VIRT_PREFIX }}"
export PATH="{{ PATH }}"
export C_INCLUDE_PATH="{{ C_INCLUDE_PATH }}"
export LD_LIBRARY_PATH="{{ LD_LIBRARY_PATH }}"
export PKG_CONFIG_PATH="{{ PKG_CONFIG_PATH }}"
export XDG_DATA_DIRS="{{ XDG_DATA_DIRS }}"
export GI_TYPELIB_PATH="{{ GI_TYPELIB_PATH }}"
export OSINFO_SYSTEM_DIR="{{ OSINFO_SYSTEM_DIR }}"
export PERL5LIB="{{ PERL5LIB }}"
export PYTHONPATH="{{ PYTHONPATH }}"

export CCACHE="{{ ccache }}"
export MAKE="{{ make }}"
export PYTHON="{{ python }}"

test "$CCACHE" && export CC="$CCACHE cc"

# Enable bash completion. Only needed on FreeBSD, the system-wide
# shell profile will take care of it for us everywhere else
bash_completion=/usr/local/share/bash-completion/bash_completion.sh
test -f "$bash_completion" && . "$bash_completion"
