export PS1="[\u@\h \w]\$ "

export VIRT_PREFIX="{{ VIRT_PREFIX }}"
export C_INCLUDE_PATH="{{ C_INCLUDE_PATH }}"
export LD_LIBRARY_PATH="{{ LD_LIBRARY_PATH }}"
export PKG_CONFIG_PATH="{{ PKG_CONFIG_PATH }}"
export XDG_DATA_DIRS="{{ XDG_DATA_DIRS }}"
export GI_TYPELIB_PATH="{{ GI_TYPELIB_PATH }}"
